Create 1D vector
Using numpy.array()

This is the primary way to create a NumPy array (vector) from existing Python data. You simply pass a list of elements to the function.

In [ ]:
import numpy as np

# Method 1: From a Python list
my_list = [10, 20, 30, 40, 50]
vector_a = np.array(my_list)
print(vector_a)
# Output: [10 20 30 40 50]
print(vector_a.shape)
# Output: (5,)  <-- The (N,) shape indicates a 1D vector of length 5

# Method 2: From a Python tuple
my_tuple = (5, 4, 3, 2, 1)
vector_b = np.array(my_tuple)
print(vector_b)
# Output: [5 4 3 2 1]

[10 20 30 40 50]
(5,)
[5 4 3 2 1]


ndarray.ndim

    the number of axes (dimensions) of the array.

ndarray.shape

    the dimensions of the array. This is a tuple of integers indicating the size of the array in each dimension. For a matrix with n rows and m columns, shape will be (n,m). The length of the shape tuple is therefore the number of axes, ndim.

ndarray.size

    the total number of elements of the array. This is equal to the product of the elements of shape.

ndarray.dtype

    an object describing the type of the elements in the array. One can create or specify dtype’s using standard Python types. Additionally NumPy provides types of its own. numpy.int32, numpy.int16, and numpy.float64 are some examples.


In [ ]:
a = np.arange(15).reshape(3, 5)

print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)

2
(3, 5)
15
int64


In [ ]:
a = np.arange(6)                    # 1d array
print(a)
b = np.arange(12).reshape(4, 3)     # 2d array
print(b)
c = np.arange(24).reshape(2, 3, 4)  # 3d array
print(c)


[0 1 2 3 4 5]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


Using Array Creation Functions

NumPy provides several functions to generate vectors with patterned or default values:

np.arange()

Similar to Python's range(), this creates a vector of evenly spaced values within a given interval.

In [ ]:
# Creates a vector from 0 (inclusive) up to 5 (exclusive)
vector_c = np.arange(5)
print(vector_c)
# Output: [0 1 2 3 4]

# Creates a vector starting at 10, up to 21, with a step of 2
vector_d = np.arange(10, 21, 2)
print(vector_d)
# Output: [10 12 14 16 18 20]

[0 1 2 3 4]
[10 12 14 16 18 20]


np.linspace()

This function creates a vector with a specified number of samples, evenly spaced between a start and end point (inclusive by default).

In [ ]:
# Creates 10 evenly spaced points between 0 and 1 (inclusive)
vector_e = np.linspace(0, 1, 10)
print(vector_e)
# Output: [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556 0.66666667 0.77777778 0.88888889 1.        ]

np.zeros() and np.ones()

These create a vector filled entirely with zeros or ones, respectively. You just need to specify the desired length (shape) as an integer.

In [ ]:
# Vector of length 4 filled with zeros
vector_f = np.zeros(4)
print(vector_f)
# Output: [0. 0. 0. 0.]

# Vector of length 3 filled with ones
vector_g = np.ones(3)
print(vector_g)
# Output: [1. 1. 1.]

The basic transformations of vectors in NumPy largely involve algebraic operations (scaling, addition) and geometric manipulations (rotation, scaling, projection) which are often implemented using matrix multiplication.

Since NumPy vectors are fundamentally arrays, the operations are often applied element-wise or through linear algebra functions provided by the numpy.linalg module.

Here are the most basic transformations:

Addition and Subtraction (Translation)

Vector addition results in a new vector that represents the combined translation of the original vectors. This is done element-wise if both are 1D arrays of the same size.

In [ ]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

# Addition: [1+4, 2+5, 3+6] = [5, 7, 9]
v_add = v1 + v2
print(v_add)

# Subtraction: [1-4, 2-5, 3-6] = [-3, -3, -3]
v_sub = v1 - v2
print(v_sub)

[5 7 9]
[-3 -3 -3]


Scalar Multiplication (Scaling)

Multiplying a vector by a scalar c scales the length of the vector by ∣c∣. If c is negative, it also reverses the vector's direction.

In [ ]:
# Scale the vector v1 by 3
v_scaled = v1 * 3
print(v_scaled)
# Output: [3 6 9]

# Scale by a negative number
v_reversed = v1 * -1
print(v_reversed)
# Output: [-1 -2 -3]

Geometric Transformations (Matrix-Based)

In linear algebra, geometric transformations like rotation, shear, and reflection are performed by multiplying the vector by a Transformation Matrix (M).

For a vector v and a transformation matrix M, the transformed vector v′ is calculated as:
v′=Mv

In NumPy, you use numpy.dot() or the @ operator for matrix-vector multiplication.

Rotation

To rotate a 2D vector v=(x,y) by an angle θ counter-clockwise, you use the 2x2 Rotation Matrix:

R(θ) = ([cosθ, -sinθ],
        [sinθ, cosθ ])

In [ ]:
# Rotate vector v by 90 degrees (pi/2 radians)
theta = np.pi / 2
R = np.array([[np.cos(theta), -np.sin(theta)],
              [np.sin(theta),  np.cos(theta)]])

v = np.array([1, 0]) # A vector along the x-axis
print(v)
v_rotated = R @ v # Use the @ operator for matrix multiplication
print(np.round(v_rotated, 5))
# Output: [0. 1.] (The vector has rotated from [1, 0] to [0, 1])

[1 0]
[0. 1.]


Shearing (Skewing)

A shear transformation moves all points in a given direction proportional to their distance from a line parallel to that direction.

In [ ]:
# Shear matrix (X-axis shear)
S = np.array([[1, 2],
              [0, 1]])

print(v)
v_sheared = S @ v
print(v_sheared)
# Output: [1 0] -> [1 0] (for this vector)

v_2d = np.array([1, 1])
v_sheared_2d = S @ v_2d
print(v_sheared_2d)
# Output: [3 1] (The original vector [1, 1] is moved to [3, 1])

[1 0]
[1 0]
[3 1]


Projecting one vector (u) onto another (v) finds the component of u that lies in the direction of v. This involves using the inner product (np.dot).


In [ ]:
# Vector u to be projected
print(u)
u = np.array([1, 5])
# Vector v onto which u is projected
print(v)
v = np.array([4, 2])

# 1. Calculate the scalar factor (u * v) / ||v||^2
scalar_factor = np.dot(u, v) / np.dot(v, v)
print(scalar_factor)

# 2. Multiply the scalar factor by v
projection = scalar_factor * v
print(np.round(projection, 3))
# Output: [1.889 0.944]

[1 5]
[4 2]
0.7
[2.8 1.4]


continue
https://numpy.org/doc/stable/user/absolute_beginners.html
https://numpy.org/numpy-tutorials/mooreslaw-tutorial/
https://www.youtube.com/watch?v=JSjWltL9-7M